service: projeto3-telegram

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.10
  profile: python-lambda-ricardo
  region: us-east-1
  stage: prod
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - ce:GetCostAndUsage
          Resource: '*'

functions:
  get_cost:
    handler: handler.get_cost
    events:
      - schedule: 
          rate: rate(1 minute)  # para teste, a cada minuto dispara
          enabled: false
          input: {}
      - schedule: 
          rate: cron(0 23 * * ? *)  # todo dia as 23h -3 = 20h brasilia
          enabled: true
          input: {}

plugins:
  - serverless-python-requirements

package: 
  patterns:
    - "!env"
    - "!node_modules"
    - "!*.json"
